[book]
authors = ["Luca Palmieri"]
language = "en"
multilingual = false
src = "src"
title = "100 Exercises To Learn Rust"

[output.html]
git-repository-url = "https://github.com/mainmatter/100-exercises-to-learn-rust"

[output.html.playground]
runnable = false
